export const messagesIntl = {
  ru: {
    COLOUR: 'Цвет',
    ERASER: 'Ластик (E)',
    ERASER_SENSITIVITY: 'Чувствительность',
    GRID: 'Фоновая сетка',
    HAND: 'Перемещение доски',
    HIGHLIGHTER: 'Маркер',
    LINE: 'Линия (L)',
    LINE_THICKNESS: 'Толщина линии',
    LOCK: 'Изменить блокировку',
    PENCIL: 'Карандаш (P)',
    SELECT: 'Выбрать (V)',
    SHAPE: 'Фигура',
    TEXT: 'Текст (T)',
    UPLOAD_IMAGE: 'Загрузить изображение',
    ZOOM_IN: 'Увеличить',
    ZOOM_OUT: 'Уменьшить',
  },
  en: {
    COLOUR: 'Colour',
    ERASER: 'Eraser (E)',
    ERASER_SENSITIVITY: 'Eraser sensitivity',
    GRID: 'Grid',
    HAND: 'Hand',
    HIGHLIGHTER: 'Highlighter',
    LINE: 'Line (L)',
    LINE_THICKNESS: 'Line thickness',
    LOCK: 'Lock',
    PENCIL: 'Pencil (P)',
    SELECT: 'Select (V)',
    SHAPE: 'Shape',
    TEXT: 'Text (T)',
    UPLOAD_IMAGE: 'Upload image',
    ZOOM_IN: 'Zoom in',
    ZOOM_OUT: 'Zoom out',
  },
  it: {
    COLOUR: 'Colore',
    ERASER: 'Gomma (E)',
    ERASER_SENSITIVITY: 'Sensibilità',
    GRID: 'Griglia',
    HAND: 'Spostare la lavagna',
    HIGHLIGHTER: 'Pennarello',
    LINE: 'Linea (L)',
    LINE_THICKNESS: 'Larghezza linea',
    LOCK: 'Bloccare/Sbloccare',
    PENCIL: 'Matita (P)',
    SELECT: 'Selezionare (V)',
    SHAPE: 'Figura',
    TEXT: 'Testo (T)',
    UPLOAD_IMAGE: 'Caricare immagine',
    ZOOM_IN: 'Ingrandire',
    ZOOM_OUT: 'Ridurre',
  },
}
